### ISSUE TITLE
Extract CCP handling into a separate extension

### ISSUE THREAD

**Issue by robertschubert** [GAIA-X4PLC-AAD/EDC-Blockchain-Catalog#6]
# Feature Request

Currently we have the CCP logic in the existing blockchain extension. The logic should be extracted into a new extension and called by the blockchain extension.
Example for creating an extension:
https://github.com/GAIA-X4PLC-AAD/EDC-Blockchain-Catalog/commit/d11c3336d62f418592ae1f1265a787e100f03816

## Why Is the Feature Desired?
Technical feature / loose coupling.

## Solution Proposal
see link above

## Type of Issue
refactoring

@JulianLegler FYI

**Comment by robertschubert** [comment]
@JulianLegler 
Did I understand right that you propose to create a separate Repository and add the new service as another git submodule?

**Comment by JulianLegler** [comment]
> @JulianLegler Did I understand right that you propose to create a separate Repository and add the new service as another git submodule?

I would have thought about it as just another folder in the extensions directory.

**Comment by robertschubert** [comment]
Oh, I already started to build it as an external independent extension I have the build for it already running. 
But I guess that's OK for you?

**Comment by robertschubert** [comment]
@JulianLegler 
I was not able to put the artifact (github package) of the https://github.com/GAIA-X4PLC-AAD/claim-compliance-provider-edc-extension repository publically available. Github only supports to read the package with a personal access token (PAT). I did not want to have a token in the build process of the blockchain catalog build.

So i integrated it directly into the EDC Blockchain Catalog repository.

I have an issue with CDI as i explained in https://github.com/GAIA-X4PLC-AAD/EDC-Blockchain-Catalog/pull/14

My temporary workaround is:
<img width="677" alt="image" src="https://github.com/user-attachments/assets/d8195353-b4ff-4d95-b80e-9386b3ea0b76">

Maybe you can have a look?
