### ISSUE TITLE
Logging: Calling "Catalog Browser" creates 2 MB log

### ISSUE THREAD

**Issue by robertschubert** [GAIA-X4PLC-AAD/EDC-Blockchain-Catalog#8]
# Bug Report

## Describe the Bug
When opening the "Catalog Browser" 2 MBs of logs are created. Log level is debug, but we can optimize here.

### Expected Behavior
The application should not log so extensive. In our azure environment we have to pay for the service "Log Analytics" which saves all logs.

### Observed Behavior
- TokenizedAsset does not contain @id
  - summarize this warning like 40 TokenizedAsset does not contain @id
- TokenziedAsset test-document-134 does not contain @context - Skipping
  - summarize this warning: following TokenziedAssets does not contain @context - Skipping: {list of ids}
- TokenizedPolicyDefinition is null or does not contain @id
  - summarize to: {count} TokenizedPolicyDefinition is null or does not contain @id
- fetching contract 109
  - set this to loglevel DEBUG
- Not able to find the Asset with id test-document-9 or policy with id d5f0472b-660d-4a16-b4bd-a426a652a7b5 for the contract 129
  -  @JulianLegler is this really SEVERE in our scenario? Or can we summarize it without the detail infos (IDs)?
- if not already possible: give the possibility to adjust the log level with ENV-Variable. 

## Steps to Reproduce
Open the Catalog Browser and view the logs.

## Possible Implementation
- I will start to investigate on the topic adjustment of loglevel.

@JulianLegler FYI. Please give me some feedback to the proposals.

**Comment by JulianLegler** [comment]
Yes I guess we can cut down a lot of these messages or omit them completely. 

### Background
Currently, the EDC is fetching all existing tokens  (Contracts, Assets, Policies) from the blockchain and then tries to "rebuild" the edc contracts from these data internally to provide the DCAT Catalog (/blockchaincatalog). During this process, all assets and policies will be parsed and checked against the contract tokens if they build together a valid edc contract. So these log messages basically reflect exact this step. And as we are extensively testing and developing lately, staying with the same blockchain address, these blockchain contracts are now filled with tokens resulting in this extensive logging. Also, as there are old versions of tokens in these blockchain contracts, they result in errors like the above-mentioned, as they don't fulfill the new mandatory fields.

Internally are we currently working on a new way to achieve this matching without this extensive comparison of all existing tokens. Until this work is finished, we could easily just, as you suggested, set the logging level for these to something very low and then raise the monitor log level at which these events are actually logged. The latter should also be possible using environment parameters.

**Comment by robertschubert** [comment]
Thanks Julian,
I was trying to adjust the loglevel with ENV variables but this seems not to work out.
I am testing the documented way now: https://github.com/eclipse-edc/Connector/tree/main/extensions/common/monitor/monitor-jdk-logger
--> adding logging.properties.

If this will be successful, i would just push it into the existing branch of the blockchain-catalog. If you prefer a separate branch let me know.

**Comment by robertschubert** [comment]
Bad news. Adding logging.properties and `-Djava.util.logging.config.file=logging.properties` didn't have any effect. Still debug logs in the log.

**Comment by JulianLegler** [comment]
In the current version at main there are actually two loggers active by accident I think. Hopefully I will able to merge #5 with my restructure branch and then we can take a look at this.

**Comment by robertschubert** [comment]
OK, thanks.
What I found out is that a "ConsoleMonitor" is used which is called by its Default Constructor which sets log level to DEBUG.
What we need is to use the "LoggerMonitor" which uses java.util.logging.Logger which can be configured by a logging.properties (already added in the fix/integrate-ccp branch which is merged.

**Comment by robertschubert** [comment]
- Managed to configure the debug level with logging.properties (https://github.com/eclipse-edc/Connector/tree/main/extensions/common/monitor/monitor-jdk-logger)
- fetching contract 109
loglevel is debug now 
- TokenizedAsset does not contain @id
loglevel is debug now
- TokenziedAsset test-document-134 does not contain @context - Skipping
loglevel is debug now
TokenizedPolicyDefinition is null or does not contain @id
loglevel is debug now
- Not able to find the Asset with id test-document-9 or policy with id d5f0472b-660d-4a16-b4bd-a426a652a7b5 for the contract 129
loglevel is debug now

@JulianLegler 
Not sure if you want to also put the logging.properties to your launcher. If yes, just copy the approach in the dockerfile. Make sure you are calling the build with the correct build context which is `edc-blockchain-broker\EDC-Blockchain-Catalog` (and not the path of the Dockerfile).
I will create the PR tomorrow after my tests.

**Comment by JulianLegler** [comment]
Thanks. I will probably take a look at it on Monday. 
I am currently engaged in refactoring the parsing of the blockchain tokens, and a lot of these spammy messages will most likely be omitted when I achieve to finish and merge it next week.

**Comment by robertschubert** [comment]
PRs:
https://github.com/GAIA-X4PLC-AAD/edc-blockchain-broker/pull/5
https://github.com/GAIA-X4PLC-AAD/EDC-Blockchain-Catalog/pull/12

**Comment by robertschubert** [comment]
PR merged, close ticket
